- name: Setup EC2 Instances for EKS Operations (Amazon Linux 2)
  hosts: ec2_instances
  become: yes
  vars:
    docker_package: docker
    kubectl_version: "1.27.0"
    aws_cli_url: "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip"

  tasks:
    - name: Update all packages
      yum:
        name: "*"
        state: latest

    - name: Install dependencies
      yum:
        name:
          - curl
          - unzip
          - wget
          - tar
        state: present

    - name: Install Docker
      yum:
        name: "{{ docker_package }}"
        state: present

    - name: Enable and start Docker
      service:
        name: docker
        enabled: yes
        state: started

    - name: Add user to docker group
      user:
        name: "{{ ansible_user }}"
        groups: docker
        append: yes

    - name: Download AWS CLI v2
      get_url:
        url: "{{ aws_cli_url }}"
        dest: /tmp/awscliv2.zip

    - name: Unzip AWS CLI
      unarchive:
        src: /tmp/awscliv2.zip
        dest: /tmp
        remote_src: yes

    - name: Install AWS CLI
      command: "/tmp/aws/install"
      args:
        creates: /usr/local/bin/aws

    - name: Install kubectl
      get_url:
        url: "https://dl.k8s.io/release/v{{ kubectl_version }}/bin/linux/amd64/kubectl"
        dest: /usr/local/bin/kubectl
        mode: '0755'
        force: yes

    - name: Verify kubectl installation
      command: kubectl version --client
      register: kubectl_output
      ignore_errors: yes

    - name: Show kubectl version output
      debug:
        var: kubectl_output.stdout
